= Configure an IPv6 floating IP for the ingress router on cloudscale

[abstract]
This how-to provides instructions for configuring an IPv6 floating ip for the ingress router of an existing cloudscale OpenShift 4 cluster.

== Prerequisites

The how-to is implemented as a Gandalf workflow.
You need to be able to run https://github.com/appuio/gandalf/[Gandalf] locally.
Both a local installation and the https://github.com/appuio/guided-setup/[guided-setup] container image should work.

IMPORTANT: The minimum required Gandalf version is v0.1.0.

NOTE: So far, the workflow has only been tested on Linux with a local Gandalf installation.


== Configuration

. Run Commodore to setup a working directory for the cluster to migrate
+
[TIP]
====
We recommend running this in an empty directory.
Alternatively, you can use an existing Commodore working directory for the cluster you want to migrate.
====
+
[source,bash]
----
export CLUSTER_ID=c-the-cluster-to-migrate-1234
commodore catalog compile $CLUSTER_ID
----

. Set the `migration_dir` environment variable so that the subsequent `gandalf` invocation is shorter.
+
[source,bash]
----
export migration_dir=\
./dependencies/openshift4-terraform/migrations/cloudscale-router-v6 <1>
----
<1> This assumes that your current working directory is the Commodore working directory for the cluster to migrate

. Run Gandalf
+
[NOTE]
====
For clusters which are located behind a SOCKS5 proxy, the workflow steps which try to access the cluster may not work correctly unless you set the `https_proxy` variable manually.
====
+
.Local Gandalf
[source,bash]
----
gandalf run "${migration_dir}/configure-router-v6.workflow" \
  ${migration_dir}/*.yaml
----
+
.Guided-setup container image
[source,bash]
----
guided-setup-base -e "migration_dir=${migration_dir}" \
  run "${migration_dir}/configure-router-v6.workflow" \
  ${migration_dir}/*.yaml
----
+
TIP: The `guided-setup-base` alias is defined in `docker/aliases.sh` in the https://github.com/appuio/guided-setup/[appuio/guided-setup] repository.
