= Upgrade cloudscale clusters to component version v10

When upgrading to component version v10 for cloudscale clusters, the following accidental breaking change requires manual changes in the Terraform state of existing clusters:

* https://github.com/appuio/terraform-modules/pull/68[Exit with error if server creation on control.vshn.net fails]

== Prerequisites

You need to be able to execute the following CLI tools locally:

* `docker`
* `yq` https://github.com/mikefarah/yq[yq YAML processor] (Version 4 or newer)
* `jq`
* `vault` https://www.vaultproject.io/docs/commands[Vault CLI]
* `terraform` https://learn.hashicorp.com/tutorials/terraform/install-cli[Terraform CLI] >= 1.3.0

== Setup environment

. Access to API
+
[source,bash]
----
# For example: https://api.syn.vshn.net
# IMPORTANT: do NOT add a trailing `/`. Commands below will fail.
export COMMODORE_API_URL=<lieutenant-api-endpoint>

export CLUSTER_ID=<lieutenant-cluster-id> # Looks like: c-<something>
export TENANT_ID=$(curl -sH "Authorization: Bearer $(commodore fetch-token)" ${COMMODORE_API_URL}/clusters/${CLUSTER_ID} | jq -r .tenant)

# From https://git.vshn.net/-/profile/personal_access_tokens, "api" scope is sufficient
export GITLAB_TOKEN=<gitlab-api-token>
export GITLAB_USER=<gitlab-user-name>
----

. Connect with Vault
+
[source,bash]
----
export VAULT_ADDR=https://vault-prod.syn.vshn.net
vault login -method=oidc
----

== Steps

. Verify that the cluster uses component `openshift4-terraform` v10.

. Get the cluster's cloudscale API token from Vault.
+
[source,bash]
----
export CLOUDSCALE_API_TOKEN=$(vault kv get -format=json \
  clusters/kv/${TENANT_ID}/${CLUSTER_ID}/cloudscale | \
  jq -r '.data.data.token')
----

. Setup Git author information and create the Terraform environment file.
+
[source,bash]
----
export GIT_AUTHOR_NAME=$(git config --global author.name)
export GIT_AUTHOR_EMAIL=$(git config --global author.email)

cat <<EOF > ./terraform.env
CLOUDSCALE_API_TOKEN
GIT_AUTHOR_NAME
GIT_AUTHOR_EMAIL
EOF
----

. Setup Terraform
+
.Prepare Terraform execution environment
[source,bash]
----
# Set terraform image and tag to be used
tf_image=$(\
  yq eval ".parameters.openshift4_terraform.images.terraform.image" \
  dependencies/openshift4-terraform/class/defaults.yml)
tf_tag=$(\
  yq eval ".parameters.openshift4_terraform.images.terraform.tag" \
  dependencies/openshift4-terraform/class/defaults.yml)

# Generate the terraform alias
base_dir=$(pwd)
alias terraform='touch .terraformrc; docker run -it --rm \
  -e REAL_UID=$(id -u) \
  -e TF_CLI_CONFIG_FILE=/tf/.terraformrc \
  --env-file ${base_dir}/terraform.env \
  -w /tf \
  -v $(pwd):/tf \
  --ulimit memlock=-1 \
  "${tf_image}:${tf_tag}" /tf/terraform.sh'

export GITLAB_REPOSITORY_URL=$(curl -sH "Authorization: Bearer $(commodore fetch-token)" ${COMMODORE_API_URL}/clusters/${CLUSTER_ID} | jq -r '.gitRepo.url' | sed 's|ssh://||; s|/|:|')
export GITLAB_REPOSITORY_NAME=${GITLAB_REPOSITORY_URL##*/}
export GITLAB_CATALOG_PROJECT_ID=$(curl -sH "Authorization: Bearer ${GITLAB_TOKEN}" "https://git.vshn.net/api/v4/projects?simple=true&search=${GITLAB_REPOSITORY_NAME/.git}" | jq -r ".[] | select(.ssh_url_to_repo == \"${GITLAB_REPOSITORY_URL}\") | .id")
export GITLAB_STATE_URL="https://git.vshn.net/api/v4/projects/${GITLAB_CATALOG_PROJECT_ID}/terraform/state/cluster"

pushd catalog/manifests/openshift4-terraform/
----
+
.Initialize Terraform
[source,bash]
----
terraform init \
  "-backend-config=address=${GITLAB_STATE_URL}" \
  "-backend-config=lock_address=${GITLAB_STATE_URL}/lock" \
  "-backend-config=unlock_address=${GITLAB_STATE_URL}/lock" \
  "-backend-config=username=${GITLAB_USER}" \
  "-backend-config=password=${GITLAB_TOKEN}" \
  "-backend-config=lock_method=POST" \
  "-backend-config=unlock_method=DELETE" \
  "-backend-config=retry_wait_min=5"
----

. Migrate the Terraform state
+
.Run the migration script
[source,bash]
----
terraform state pull > state.json
jq -r '.serial = .serial + 1' state.json > newstate.json
sed -i 's/e797eceb31caa97793cbc305701c027e216b8bb0/60dca4e2605a199c436349ad293b42a33745e4a8/' newstate.json
terraform state push newstate.json
----
+
.Verify state using `plan`
[source,bash]
----
terraform plan
----
+
You can expect the following changes:
+
* The LB hieradata repo will be checked out
* The LB hieradata will get created
+
TIP: You don't need to run `terraform apply` for this migration.

. Cleanup the local state JSON files
+
[source,bash]
----
rm state.json newstate.json
----
