= Use Exoscale

IMPORTANT: Currently the Terraform module which this component uses for Exoscale only supports provisioning VSHN-managed OCP4 clusters on Exoscale.

NOTE: See https://kb.vshn.ch/oc4/how-tos/exoscale/install.html[the Exoscale installation how-to] for a comprehensive how-to for setting up OCP4 on Exoscale.

The following steps show how to set up Terraform with Exoscale.

NOTE: The component currently assumes that the Git repositories live on a GitLab instance.

== Setup credentials

. Set up 2 new API keys in https://portal.exoscale.com[portal.exoscale.com].
They're used for the Terraform pipeline.
.. The first key should be created with restricted permissions:
+
- compute
  * `get*`
  * `list*`
  * `query*`
  * `show*`
  * `validate*`
- DNS
  * `list*`
  * `get*`
.. The second key can be created as `unrestricted`.

include::partial$puppet-lb-cred.adoc[]

== Setup component

. Configure component parameters
+
[source,yaml]
----
openshift4_terraform:
  provider: exoscale
  gitlab_ci:
    git: <1>
      username: Max Mustermann
      email: mm@example.com
  terraform_variables:
    # Required parameters
    rhcos_template: TheTemplateNameForRHCOS
    base_domain: ${openshift:baseDomain}
    ignition_ca: |-
      -----BEGIN CERTIFICATE-----
      ...
    ssh_key: ssh-ed25519 AA...
    bootstrap_bucket: https://sos-${facts:region}.exo.io/${cluster:name}-bootstrap
    hieradata_repo_user: project_123_bot <2>

    # Optional parameters:
    worker_count: 3
    worker_size: Extra-large
----
<1> The Git author name and email address.
Used when creating hieradata commits.
If not specified, the GitLab CI defaults will be used.
<2> The user created for the hieradata project access token.
Please note that the Terraform module currently only supports the https://git.vshn.net/appuio/appuio_hieradata[VSHN APPUiO hieradata]

. Compile the cluster catalog
. Configure the cluster catalog GitLab repository CI/CD
  - "Settings > CI/CD > General pipelines > Configuration file" +
    `manifests/openshift4-terraform/gitlab-ci.yml`
  - "Settings > CI/CD > Variables"
    * `EXOSCALE_API_SECRET_RO`
    * `EXOSCALE_API_KEY_RO`
    * `EXOSCALE_API_SECRET_RW`
    * `EXOSCALE_API_KEY_RW`
    * `HIERADATA_REPO_TOKEN` -- the VSHN APPUiO hieradata project access token
    * `CONTROL_VSHN_NET_TOKEN`
